language: java
jdk:
  - oraclejdk11

before_install:
  - chmod rwx gradlew

install: skip

script:
  - ./gradlew build

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
email:
recipients:
  - leonardocm92@hotmail.com
on_success: always
on_failure: always